name: CI

on:
  push:
    branches: [ main ]
    tags-ignore: [ '*' ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Install Test Libraries
      run: pip install tox

    - name: Run Tests
      run: tox

    - name: Generate coverage report
      if: matrix.os == 'ubuntu-latest'
      run: |
        pip install pytest pytest-cov
        dotnet tool install -g dotnet-reportgenerator-globaltool

        pytest --cov-report xml
        reportgenerator -reports:"./coverage.xml" -targetdir:"./artifacts" -reporttypes:"MarkdownSummaryGithub;TextSummary"

    - name: Report coverage
      if: matrix.os == 'ubuntu-latest'
      run: |
        cat "./artifacts/Summary.txt"
        cat "./artifacts/SummaryGithub.md" > $GITHUB_STEP_SUMMARY

    - name: Install build Libraries
      run: pip install build

    - name: Create Artifacts
      run: python -m build

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: dist
        retention-days: 1
