name: CI

on:
  push:
    branches: [ main ]
    tags-ignore: [ '**' ]
    paths-ignore:
      - '.devcontainer/**'
      - '..devcontainer-compose/**'
      - '.github/**'
      - '.vscode/**'
      - '.editorconfig'
      - '.gitignore'
      - '.lefthook.yml'
      - 'devbox.json'
      - 'LICENSE'
      - 'README.md'
  pull_request:

permissions:
  contents: read

jobs:
  ubuntu:
    uses: 9506hqwy/actions/.github/workflows/python-ci-ubuntu.yml@main

  windows:
    uses: 9506hqwy/actions/.github/workflows/python-ci-windows.yml@main
